set(SIGNALS_INCLUDE_DIRS ${CMAKE_CURRENT_SOURCE_DIR}/include CACHE PATH "Where to find the Signals headers")
set(HEADERS Signals )
foreach(h ${HEADERS})
    list(APPEND KTB_HEADERS ${SIGNALS_INCLUDE_DIRS}/${h}.hpp)
endforeach()
set(KTB_HEADERS ${KTB_HEADERS} PARENT_SCOPE)
set(KTB_SRCS ${KTB_SRCS} PARENT_SCOPE)
